#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: ./add 'Problem Title With Spaces'"
    exit 1
fi

name=$(echo -n "$1" | sed 's/ /_/g')

code=$(cat <<EOF
#include <bits/stdc++.h>

using namespace std;

int main() {
    int n;
    cin >> n;

    for (int i = 0; i != n; ++i) {
        int x;
        cin >> x;
    }
}
EOF
)

makefile=$(cat <<EOF
build:
	g++ -std=c++17 -g -O -Wall -Weffc++ -pedantic -pedantic-errors -Wextra -Wcast-align -Wcast-qual  -Wchar-subscripts -Wcomment -Wconversion -Wdisabled-optimization -Werror -Wfloat-equal -Wformat -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wunsafe-loop-optimizations -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wpacked -Wparentheses -Wpointer-arith -Wredundant-decls -Wreturn-type -Wsequence-point  -Wshadow -Wsign-compare -Wstack-protector -Wstrict-aliasing -Wstrict-aliasing=2 -Wswitch -Wswitch-default -Wswitch-enum -Wtrigraphs -Wuninitialized -Wunknown-pragmas -Wunreachable-code -Wunused -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -Wvariadic-macros -Wvolatile-register-var -Wwrite-strings -o ./solution ./solution.cpp

run: build
	./solution
EOF
)

mkdir "./$name"
cd "./$name"
echo "$code" > ./solution.cpp
echo "$makefile" > ./Makefile
echo "cd ./$name && make run"
