#!/usr/bin/env python3

import argparse
import os
import re

parser = argparse.ArgumentParser()
parser.add_argument("-a", "--atcoder",
                    help="Assume the crates available at AtCoder",
                    action="store_true")
parser.add_argument("-e", "--embed",
                    help="Assume running in a “0 crates available” mode; embed input scanner",
                    action="store_true")
parser.add_argument("-p", "--prefix-output",
                    help="Read STDIN & prefix K-th test case's output with `Case #K: `",
                    action="store_true")
parser.add_argument("name", help="The name of the problem")
args = parser.parse_args()

code = ""

if args.prefix_output:
    code = code + """use proconio::input;
// use proconio::marker::Bytes;
use proconio_derive::fastout;


fn solve(xs: &[i32]) -> i32 {
    xs.iter().sum::<i32>()
}

#[fastout]
fn main() {
    input! {
        cases_num: u16,
    }

    for t in 1..=cases_num {
        input! {
            n: usize,
            xs: [i32; n],
        }

        let result = solve(&xs);
        println!("Case #{}: {}", t, result);
    }
}
"""
elif args.embed:
    code += """use std::io::{self, stdin, BufWriter, Write};

#[derive(Default)]
struct Scanner {
    buffer: Vec<String>,
}

impl Scanner {
    fn next<T: std::str::FromStr>(&mut self) -> T {
        loop {
            if let Some(token) = self.buffer.pop() {
                return token.parse().ok().expect("Failed parse");
            }
            let mut input = String::new();
            stdin().read_line(&mut input).expect("Failed read");
            self.buffer = input.split_whitespace().rev().map(String::from).collect();
        }
    }
}

fn solve(xs: &[i32]) -> i32 {
    xs.iter().sum::<i32>()
}

fn main() {
    let stdout = io::stdout();
    let handle = stdout.lock();
    let mut writer = BufWriter::new(handle);

    let mut scanner = Scanner::default();
    let cases_num: u16 = scanner.next();

    for _ in 1..=cases_num {
        let n: usize = scanner.next();
        let mut xs: Vec<i32> = vec![0; n];
        for x in xs.iter_mut() {
            *x = scanner.next();
        }

        let result = solve(&xs);
        writeln!(writer, "{}", result).unwrap();
    }

    writer.flush().unwrap();
}
"""
elif args.atcoder:
    code += """use std::io::{self, BufWriter, Write};
use proconio::input;
// use proconio::marker::Bytes;

fn solve(xs: &[i32]) -> i32 {
    xs.iter().sum::<i32>()
}

fn main() {
    let stdout = io::stdout();
    let handle = stdout.lock();
    let mut writer = BufWriter::new(handle);

    input! {
        n: usize,
        xs: [i32; n],
    }

    let result = solve(&xs);
    writeln!(writer, "{}", result).unwrap();
    writer.flush().unwrap();
}
"""
else:
    code += """use std::io::{self, BufRead};

fn main() {
    let grid: Vec<Vec<char>> = io::stdin()
        .lock()
        .lines()
        .map(|line| line.unwrap().chars().collect())
        .collect();
}
"""

def normalize(name):
    ans = name
    muted = "!#$%^*()'!?:."
    for x in muted:
        ans = ans.replace(x, '')
    return re.sub(r'[ &,]+', '_', ans)

os.system('cargo new {0} --name solution'.format(normalize(args.name)))
path = os.path.join(os.getcwd(), normalize(args.name))
os.chdir(path)

if args.atcoder:
    os.system('cargo add proconio')

if args.prefix_output:
    os.system('cargo add proconio')
    os.system('cargo add proconio_derive')

with open("src/main.rs", "w+") as file:
    file.write(code)

os.system('pwd | xclip -selection clipboard')
os.system('emacsclient -n ./src/main.rs')

clipboard_command = """echo 'cd ./{0} && cargo build' | xclip -selection clipboard""".format(normalize(args.name))
os.system(clipboard_command)
