build:
	g++ -I/home/ikr/code/ac-library -std=gnu++17 -Wall -Wextra -Wshadow -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -pedantic -Wcast-qual -Wcast-align -O2 -o ./solution ./solution.cpp

run: build
	./solution
