#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: ./add 'Problem Title With Spaces'"
    exit 1
fi

name=$(echo -n "$1" | sed 's/ /_/g')

code=$(cat <<EOF
#include <bits/stdc++.h>

using namespace std;

int main() {
    int n;
    cin >> n;

    vector<int> xs(n);

    for (auto &x : xs) {
        cin >> x;
    }

    cout << xs[0] << ".." << xs.back() << '\n';
}
EOF
)

makefile=$(cat <<EOF
build:
	g++ -std=gnu++17 -Wall -Wextra -Wshadow -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -pedantic -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2 -O2 -fsanitize=address -fsanitize=undefined -fno-sanitize-recover -fstack-protector -o ./solution ./solution.cpp

run: build
	./solution
EOF
)

mkdir "./$name"
cd "./$name"
echo "$code" > ./solution.cpp
echo "$makefile" > ./Makefile
echo '-std=c++14' > ./compile_flags.txt
echo "cd ./$name && make run"
