build:
	g++ -fno-stack-limit -Wall -Wextra -std=gnu++17 -pedantic-errors -o ./solution ./solution.cpp
	g++ -Wall -Wextra -std=gnu++17 -pedantic-errors -o ./gen_input ./gen_input.cpp

run: build
	./solution
